-- Script pentru importarea cursurilor existente în baza de date
-- Rulează acest script în Supabase SQL Editor după ce ai creat tabelul courses

-- Șterge cursurile existente dacă vrei să reimportezi (opțional)
-- DELETE FROM courses;

-- Import cursuri
INSERT INTO courses (
  id,
  name,
  name_ru,
  short_description,
  short_description_ru,
  duration,
  duration_ru,
  price,
  currency,
  price_alt,
  level,
  available,
  features,
  features_ru,
  detailed_description,
  detailed_description_ru,
  what_you_learn,
  what_you_learn_ru,
  effects,
  effects_ru,
  what_you_get,
  what_you_get_ru,
  practice_models,
  support_days,
  includes_branding,
  includes_career_strategy,
  includes_portfolio,
  diploma,
  display_order
) VALUES
-- 1. Start-Up
(
  gen_random_uuid(),
  'Start-Up',
  'Start-Up',
  'Inițiere în extensii de gene (3 zile)',
  'Введение в наращивание ресниц (3 дня)',
  '3 zile',
  '3 дня',
  330.00,
  'EUR',
  '6600 MDL',
  'beginner',
  true,
  '["Teorie de bază", "Aplicare pe manechin", "3 modele reale"]'::jsonb,
  '["Базовая теория", "Применение на манекене", "3 реальные модели"]'::jsonb,
  'Primii pași în carieră. Practică reală. Zero riscuri. Vrei să încerci domeniul extensiilor de gene, dar nu știi dacă este pentru tine? „Start UP" este un curs de inițiere creat special pentru începătoarele absolute care vor să testeze acest domeniu într-un cadru profesionist, fără investiții riscante.',
  'Первые шаги в карьере. Настоящая практика. Нулевые риски. Хочешь попробовать сферу наращивания ресниц, но не знаешь, подходит ли она тебе? "Start UP" - это вводный курс, созданный специально для новичков, которые хотят протестировать эту сферу в профессиональной среде, без рискованных инвестиций.',
  '["Teorie: Igienă, produse și noțiuni de bază", "Aplicare pe manechin + 3 modele reale", "Greșeli frecvente și cum le eviți", "Suport în crearea kitului pentru începători"]'::jsonb,
  '["Теория: Гигиена, продукты и основные понятия", "Применение на манекене + 3 реальные модели", "Частые ошибки и как их избежать", "Поддержка в создании стартового набора"]'::jsonb,
  '["1D", "2D", "Efect umed"]'::jsonb,
  '["1D", "2D", "Мокрый эффект"]'::jsonb,
  '["Diplomă de participare", "Fișă personalizată de progres", "Recomandări individuale pentru dezvoltare", "Bonus: reducere dacă alegi un curs mai avansat"]'::jsonb,
  '["Диплом участия", "Персонализированная карта прогресса", "Индивидуальные рекомендации для развития", "Бонус: скидка при выборе более продвинутого курса"]'::jsonb,
  3,
  30,
  false,
  false,
  false,
  'participation',
  1
),
-- 2. Next-Up
(
  gen_random_uuid(),
  'Next-Up',
  'Next-Up',
  'Tehnica extensiilor de gene de la zero (5 zile)',
  'Техника наращивания ресниц с нуля (5 дней)',
  '5 zile',
  '5 дней',
  550.00,
  'EUR',
  '11000 MDL',
  'beginner',
  true,
  '["Teorie completă", "7 modele reale", "Suport 60 zile"]'::jsonb,
  '["Полная теория", "7 реальных моделей", "Поддержка 60 дней"]'::jsonb,
  'Curs 100% practic, orientat spre rezultate comerciale rapide. Acest curs este dedicat începătoarelor care vor să învețe să aplice extensii de gene corect, eficient și cu scop profesional. Tot ce înveți, vei pune în aplicare. Te învățam pas cu pas, iar rezultatul final este o lucrare comercială reală.',
  '100% практический курс, ориентированный на быстрые коммерческие результаты. Этот курс предназначен для новичков, которые хотят научиться правильно, эффективно и профессионально наращивать ресницы. Все, что изучаешь, применяешь на практике. Мы обучаем пошагово, а конечный результат - настоящая коммерческая работа.',
  '["Igienă, produse, tipuri de aplicare", "Izolare perfectă și poziționare corectă", "Aplicare pe manechin + 7 modele reale", "Identificarea și corectarea greșelilor", "Pregătirea pentru lucrul cu clienți reali"]'::jsonb,
  '["Гигиена, продукты, типы применения", "Идеальная изоляция и правильное позиционирование", "Применение на манекене + 7 реальных моделей", "Выявление и исправление ошибок", "Подготовка к работе с реальными клиентами"]'::jsonb,
  '["1D", "2D", "3D", "4-6D", "Volum", "Efect de raze", "Efect umed", "Perfect line", "2 tehnici de formare a evantailor", "2 tehnici de aplicare a evantailor"]'::jsonb,
  '["1D", "2D", "3D", "4-6D", "Объем", "Лучевой эффект", "Мокрый эффект", "Идеальная линия", "2 техники формирования веера", "2 техники применения веера"]'::jsonb,
  '["Diplomă de absolvire", "Fișă de progres personalizată", "Suport timp de 60 zile", "Recomandări pentru dezvoltare și achiziționare materiale"]'::jsonb,
  '["Диплом об окончании", "Персонализированная карта прогресса", "Поддержка в течение 60 дней", "Рекомендации по развитию и приобретению материалов"]'::jsonb,
  7,
  60,
  false,
  false,
  false,
  'completion',
  2
),
-- 3. Academia Lash Pro
(
  gen_random_uuid(),
  'Academia Lash Pro',
  'Academia Lash Pro',
  'Program intensiv de 15 zile',
  'Интенсивная программа 15 дней',
  '15 zile',
  '15 дней',
  1500.00,
  'EUR',
  '30000 MDL',
  'advanced',
  true,
  '["12+ modele reale", "Branding personal", "Mentorat 3 luni"]'::jsonb,
  '["12+ реальных моделей", "Личный брендинг", "Менторство 3 месяца"]'::jsonb,
  'Academia completă pentru viitoarele meștere de elită. Acesta este cel mai avansat program de formare din cadrul Address Beauty — dedicat celor care își doresc o carieră în domeniul lash, nu doar un hobby. Cursul acoperă toate etapele profesionale: tehnică, practică, imagine, branding și strategii de dezvoltare.',
  'Полная академия для будущих мастеров элитного уровня. Это самая продвинутая программа обучения в Address Beauty — для тех, кто хочет построить карьеру в сфере lash, а не просто хобби. Курс охватывает все профессиональные этапы: технику, практику, имидж, брендинг и стратегии развития.',
  '["Teorie completă + aplicare practică pe peste 12 modele reale", "Izolare, simetrie, mixări, texturi comerciale", "Branding personal: conținut foto, Reels, Instagram", "Strategii de atragere a clienților și poziționare pe piață", "Corecturi zilnice, feedback individual și mentorat", "Teme pentru acasă în zilele la distanță"]'::jsonb,
  '["Полная теория + практическое применение на 12+ реальных моделях", "Изоляция, симметрия, миксы, коммерческие текстуры", "Личный брендинг: фото контент, Reels, Instagram", "Стратегии привлечения клиентов и позиционирование на рынке", "Ежедневные коррекции, индивидуальная обратная связь и менторство", "Домашние задания в дистанционные дни"]'::jsonb,
  '["1D", "2D", "3D", "4-6D", "Volum", "Efect de raze", "Efect umed", "Perfect line", "Ombre", "Anime", "Lucrări comerciale etc..."]'::jsonb,
  '["1D", "2D", "3D", "4-6D", "Объем", "Лучевой эффект", "Мокрый эффект", "Идеальная линия", "Омбре", "Аниме", "Коммерческие работы и др."]'::jsonb,
  '["Diplomă profesională recunoscută", "Portofoliu de lucrări (posibil photoshoot profesional)", "Mentorat intensiv timp de 3 luni după finalizarea cursului", "Încredere, structură, rezultate reale"]'::jsonb,
  '["Признанный профессиональный диплом", "Портфолио работ (возможна профессиональная фотосессия)", "Интенсивное менторство в течение 3 месяцев после завершения курса", "Уверенность, структура, реальные результаты"]'::jsonb,
  12,
  90,
  true,
  true,
  true,
  'professional',
  3
),
-- 4. Laminare Gene
(
  gen_random_uuid(),
  'Laminare Gene',
  'Ламинирование Ресниц',
  'Specializare laminare (2 zile)',
  'Специализация ламинирование (2 дня)',
  '2 zile',
  '2 дня',
  200.00,
  'EUR',
  '4000 MDL',
  'intermediate',
  true,
  '["Tehnică laminare", "5 modele reale", "Certificat specializare"]'::jsonb,
  '["Техника ламинирования", "5 реальных моделей", "Сертификат специализации"]'::jsonb,
  'Curs specializat în tehnica laminării genelor - procedura care oferă gene naturale, curbate și voluminoase fără extensii. Ideal pentru meșterii care vor să-și extindă gama de servicii cu o tehnică foarte căutată și profitabilă.',
  'Специализированный курс по технике ламинирования ресниц - процедуре, которая делает натуральные ресницы изогнутыми и объемными без наращивания. Идеально для мастеров, которые хотят расширить спектр услуг востребованной и прибыльной техникой.',
  '["Teoria și practica laminării genelor", "Selectarea produselor și instrumentelor", "Tehnici de aplicare și timing", "Sfaturi pentru întreținere și rezultate durabile"]'::jsonb,
  '["Теория и практика ламинирования ресниц", "Выбор продуктов и инструментов", "Техники применения и тайминг", "Советы по уходу и долговременным результатам"]'::jsonb,
  '["Laminare clasică", "Botox pentru gene", "Lifting gene"]'::jsonb,
  '["Классическое ламинирование", "Ботокс для ресниц", "Лифтинг ресниц"]'::jsonb,
  '["Certificat de specializare", "Manual de proceduri", "Recomandări pentru produse", "Suport post-curs"]'::jsonb,
  '["Сертификат специализации", "Руководство по процедурам", "Рекомендации по продуктам", "Послекурсовая поддержка"]'::jsonb,
  5,
  30,
  false,
  false,
  false,
  'completion',
  4
),
-- 5. Curs de Perfecționare
(
  gen_random_uuid(),
  'Curs de Perfecționare',
  'Курс Совершенствования',
  'Tehnici avansate (2 zile)',
  'Продвинутые техники (2 дня)',
  '2 zile',
  '2 дня',
  250.00,
  'EUR',
  '5000 MDL',
  'advanced',
  true,
  '["Tehnici avansate", "Corectarea erorilor", "Optimizare workflow"]'::jsonb,
  '["Продвинутые техники", "Исправление ошибок", "Оптимизация рабочего процесса"]'::jsonb,
  'Curs avansat destinat meșterilor cu experiență care vor să-și perfecționeze tehnicile, să învețe noi metode și să-și optimizeze procesul de lucru. Focalizat pe calitate, eficiență și rezultate comerciale superioare.',
  'Продвинутый курс для опытных мастеров, которые хотят усовершенствовать свои техники, изучить новые методы и оптимизировать рабочий процесс. Фокус на качестве, эффективности и превосходных коммерческих результатах.',
  '["Tehnici avansate de volum și texturi", "Optimizarea timpului de lucru", "Corectarea și refacerea lucrărilor", "Noi tendințe și stiluri"]'::jsonb,
  '["Продвинутые техники объема и текстур", "Оптимизация рабочего времени", "Коррекция и переделка работ", "Новые тенденции и стили"]'::jsonb,
  '["Mega volum", "Texturi mixte", "Efecte artistice", "Stiluri trendy"]'::jsonb,
  '["Мега объем", "Смешанные текстуры", "Художественные эффекты", "Трендовые стили"]'::jsonb,
  '["Certificat de perfecționare", "Acces la grup privat de mașteri", "Materiale de lucru premium", "Consultanță business"]'::jsonb,
  '["Сертификат усовершенствования", "Доступ к приватной группе мастеров", "Премиум рабочие материалы", "Бизнес-консультации"]'::jsonb,
  4,
  45,
  false,
  true,
  false,
  'professional',
  5
),
-- 6. Curs în Pregătire
(
  gen_random_uuid(),
  'Curs în Pregătire',
  'Готовящийся Курс',
  'Anunț în curând',
  'Анонс скоро',
  'TBD',
  'TBD',
  0.00,
  'EUR',
  'TBD',
  'beginner',
  false,
  '["În dezvoltare"]'::jsonb,
  '["В разработке"]'::jsonb,
  'Un nou curs inovator este în pregătire. Urmărește-ne pentru a fi primul care află detaliile!',
  'Новый инновационный курс готовится. Следи за нами, чтобы первым узнать подробности!',
  '["Detalii vor fi anunțate în curând"]'::jsonb,
  '["Детали будут объявлены в ближайшее время"]'::jsonb,
  '["TBD"]'::jsonb,
  '["TBD"]'::jsonb,
  '["TBD"]'::jsonb,
  '["TBD"]'::jsonb,
  0,
  0,
  false,
  false,
  false,
  'participation',
  6
);

-- Verifică cursurile importate
SELECT id, name, level, price, available, display_order 
FROM courses 
ORDER BY display_order;
