import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'RO' | 'RU';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  RO: {
    // Header
    'header.home': 'Acasă',
    'header.shop': 'Magazin online',
    'header.courses': 'Cursuri',
    'header.about': 'Despre noi',
    'header.delivery': 'Livrare / Achitare',
    'header.contact': 'Contact',
    'header.cart': 'Coș',
    'header.account': 'Contul meu',
    'header.register': 'Înregistrare',
    'header.login': 'Autentificare',
    'header.motto': 'Inspirație, educație și produse într-un singur loc!',
    
    // Homepage
    'home.hero.title': 'Adress Beauty',
    'home.hero.motto': 'Inspirație, educație și produse într-un singur loc!',
    'home.hero.shop': 'Magazin Online',
    'home.hero.courses': 'Cursuri Profesionale',
    'home.hero.contact': 'Contacte',
    'home.why.title': 'De ce să alegi Adress Beauty?',
    'home.why.subtitle': 'Suntem mai mult decât un brand – suntem o misiune de a oferi cele mai bune produse și servicii beauty din Moldova.',
    'home.shop.title': 'Magazin Profesional',
    'home.shop.description': 'Peste 1000 de produse premium pentru extensii de gene, sprâncene și cosmetice profesionale.',
    'home.shop.button': 'Explorează Produsele',
    'home.education.title': 'Educație de Calitate',
    'home.education.description': '6 programe de cursuri, de la începători la nivel profesional. Diplomă recunoscută și suport continuu.',
    'home.education.button': 'Vezi Cursurile',
    'home.services.title': 'Servicii Salon',
    'home.services.description': 'Servicii profesionale în salonul nostru fizic cu cele mai noi tehnici și produse premium.',
    'home.services.button': 'Programează-te',
    'home.cta.title': 'Începe transformarea ta profesională astăzi',
    'home.cta.subtitle': 'Alătură-te comunității noastre de profesioniști beauty și descoperă tot ce ai nevoie pentru succesul tău.',
    'home.cta.course': 'Rezervă un Curs',
    'home.cta.products': 'Explorează Produsele',
    
    // Homepage Carousel
    'home.carousel.title': 'Descoperă Ofertele Noastre',
    'home.carousel.description': 'Promoții exclusive, produse noi și conținut educațional pentru a-ți îmbunătăți experiența de frumusețe',
    'home.carousel.promotion': 'Promoție',
    'home.carousel.new-product': 'Produs Nou',
    'home.carousel.video': 'Video',
    
    // Online Store
    'store.title': 'Magazin Online',
    'store.description': 'Descoperă produse profesionale pentru gene false de cea mai înaltă calitate',
    'store.categories.all': 'Toate',
    'store.categories.lashes': 'Gene',
    'store.categories.lashes.subtitle': 'Extensii & Accesorii',
    'store.categories.brows': 'Sprâncene',
    'store.categories.brows.subtitle': 'Henă & Vopsele',
    'store.categories.lamination': 'Laminare',
    'store.categories.lamination.subtitle': 'Soluții & Kit-uri',
    'store.categories.care': 'Îngrijire',
    'store.categories.care.subtitle': 'Cosmetice & Skincare',
    
    // Courses
    'courses.title': 'Cursuri Beauty',
    'courses.subtitle': 'La Adress Beauty credem în puterea educației de calitate.',
    'courses.description': 'Cursurile noastre sunt concepute pentru a oferi nu doar informații, ci și o transformare profesională reală.',
    'courses.level.beginner': 'Începător',
    'courses.level.intermediate': 'Intermediar',
    'courses.level.advanced': 'Avansat',
    'courses.status.preparing': 'În pregătire',
    'courses.models': 'modele',
    'courses.details': 'Vezi Detalii',
    'courses.coming.soon': 'În curând',
    'courses.reserve': 'Rezervă Locul: +373 68 88 24 90',
    'courses.email': 'Email: addressbeauty@mail.ru',
    'courses.schedule.visit': 'Programează o Vizită',
    'courses.description.title': 'Descriere',
    'courses.what.learn': 'Ce înveți',
    'courses.effects.volumes': 'Efecte și Volume',
    'courses.what.get': 'Ce primești',
    'courses.comparison.title': 'Comparație Cursuri',
    'courses.comparison.element': 'Element',
    'courses.cta.title': 'Gata să-ți începi transformarea profesională?',
    'courses.cta.description': 'Alege cursul potrivit pentru tine și fă primul pas către o carieră de succes în beauty!',
    'courses.call.now': 'Sună acum: +373 68 88 24 90',
    'courses.write.us': 'Scrie-ne: addressbeauty@mail.ru',
    
    // About
    'about.title': 'Despre Adress Beauty',
    'about.subtitle': 'Adress Beauty este mai mult decât un brand – este o misiune.',
    'about.description': 'Ne-am propus să oferim cele mai bune produse, cele mai bine structurate cursuri și cele mai apreciate servicii beauty din Moldova. Suntem dedicați să transformăm pasiunea pentru frumusețe într-o carieră de succes pentru fiecare client.',
    'about.achievements.clients': 'Clienți mulțumiți',
    'about.achievements.students': 'Cursanți absolvenți',
    'about.achievements.products': 'Produse premium',
    'about.achievements.experience': 'Ani de experiență',
    'about.mission.title': 'Misiunea Noastră',
    'about.mission.description': 'Să oferim educație de înaltă calitate, produse premium și servicii excepționale în domeniul beauty, creând o comunitate de profesioniști pasionați care transformă vietile oamenilor prin frumusețe și încredere în sine.',
    'about.vision.title': 'Viziunea Noastră',
    'about.vision.description': 'Să devenim cea mai respectată și iubită academie beauty din Moldova, recunoscută pentru standardele înalte de calitate, inovație și dedicarea către succesul fiecărui student și client.',
    'about.values.title': 'Valorile Noastre',
    'about.values.subtitle': 'Principiile care ne ghidează în fiecare zi și în fiecare interacțiune cu clienții noștri',
    'about.team.title': 'Echipa Noastră',
    'about.team.subtitle': 'Profesioniști dedicați cu experiență vastă și pasiune pentru perfecțiune',
    'about.education': 'Educație:',
    'about.age': 'Vârsta:',
    'about.salon.title': 'Salonul Nostru',
    'about.salon.subtitle': 'Un spațiu modern, curat și relaxant, conceput pentru confortul și satisfacția clienților',
    'about.cta.title': 'Alătură-te Comunității Adress Beauty',
    'about.cta.description': 'Fie că vrei să înveți, să cumperi produse premium sau să beneficiezi de serviciile noastre, suntem aici pentru tine!',
    'about.cta.courses': 'Vezi Cursurile',
    'about.cta.shop': 'Explorează Magazinul',
    'about.cta.contact': 'Contactează-ne',
    
    // Contact
    'contact.title': 'Contactează-ne',
    'contact.description': 'Suntem aici pentru tine! Contactează-ne pentru orice întrebare despre cursuri, produse sau servicii. Echipa noastră îți va răspunde în cel mai scurt timp.',
    'contact.quick.book': 'Programează o Consultație',
    'contact.quick.book.desc': 'Consultație gratuită pentru cursuri',
    'contact.quick.order': 'Comandă Produse',
    'contact.quick.order.desc': 'Peste 1000 produse premium',
    'contact.quick.info': 'Informații Cursuri',
    'contact.quick.info.desc': '6 programe specializate',
    'contact.info.title': 'Informații de Contact',
    'contact.social.title': 'Urmărește-ne',
    'contact.location.title': 'Locația Noastră',
    'contact.map.interactive': 'Hartă interactivă',
    'contact.map.google': 'Google Maps va fi integrată',
    'contact.map.button': 'Vezi pe Google Maps',
    'contact.address.title': 'Adress Beauty',
    'contact.address.location': 'mun. Chișinău, sec. Buiucani',
    'contact.address.street': 'str. Costin Nicolae',
    'contact.form.title': 'Trimite-ne un Mesaj',
    'contact.form.name': 'Nume complet *',
    'contact.form.name.placeholder': 'Numele și prenumele',
    'contact.form.email': 'Email *',
    'contact.form.email.placeholder': 'adresa@email.com',
    'contact.form.phone': 'Telefon',
    'contact.form.phone.placeholder': '+373 XX XXX XXX',
    'contact.form.type': 'Tipul întrebării',
    'contact.form.type.placeholder': 'Selectează categoria',
    'contact.form.subject': 'Subiect *',
    'contact.form.subject.placeholder': 'Subiectul mesajului',
    'contact.form.message': 'Mesaj *',
    'contact.form.message.placeholder': 'Descrie-ne întrebarea sau solicitarea ta...',
    'contact.form.submit': 'Trimite Mesajul',
    'contact.form.submitting': 'Se trimite...',
    'contact.policies.title': 'Politici și Informații Legale',
    
    // Category Products Page
    'category.search.placeholder': 'Caută produse...',
    'category.filters.title': 'Filtre',
    'category.filters.curvature': 'Curbură',
    'category.filters.length': 'Lungime',
    'category.filters.thickness': 'Grosime',
    'category.filters.brand': 'Brand',
    'category.sort.newest': 'Noutăți',
    'category.sort.price.low': 'Preț crescător',
    'category.sort.price.high': 'Preț descrescător',
    'category.sort.popular': 'Cele mai vândute',
    'category.show.all': 'Toate',
    'category.show.out.of.stock': 'Arată produse indisponibile',
    'category.reset.filters': 'Reset Filtre',
    'category.show.all.subcategories': 'Arată toate',
    'category.hide.subcategories': 'Ascunde',
    'category.subcategories.count': 'categorii',
    'category.show.less': 'Arată mai puține',
    
    // Add Product Button
    'add.product.title': 'Adaugă produs',
    'add.product.description': 'Completează datele produsului',
    'add.product.category': 'Categorie',
    'add.product.category.placeholder': 'Selectează categoria',
    'add.product.continue': 'Continuă',
    
    // Checkout Page - Additional
    'checkout.address.placeholder': 'Strada, numărul, blocul, scara, etajul, apartamentul',
    'checkout.city.placeholder': 'Orașul',
    'checkout.firstname.placeholder': 'Introdu prenumele',
    'checkout.lastname.placeholder': 'Introdu numele',
    'checkout.notes.placeholder': 'Instrucțiuni speciale pentru livrare sau alte observații...',
    'checkout.agree.terms': 'Accept',
    'checkout.agree.terms.link': 'termenii și condițiile',
    'checkout.agree.privacy': 'și',
    'checkout.agree.privacy.link': 'politica de confidențialitate',
    
    // Admin Products Table
    'admin.search.placeholder': 'Caută după nume sau SKU...',
    'admin.delete.product': 'Șterge produs',
    'admin.deleting': 'Ștergere...',
    'admin.delete': 'Șterge',
    'admin.no.products': 'Nu s-au găsit produse pentru criteriile curente.',
    
    // Product Page
    'product.select.variant': 'Selectează varianta',
    'product.curvature': 'Curbură',
    'product.thickness': 'Grosime',
    'product.length': 'Lungime',
    
    // Product Edit Dialog
    'product.edit.description': 'Descriere',
    'product.edit.description.placeholder': 'Introduceți descrierea produsului...',
    'product.edit.image.placeholder': 'Introduceți URL-ul imaginii sau datele Base64...',
    'product.edit.price': 'Preț (MDL)',
    'product.edit.discount': 'Discount (%)',
    'product.edit.store.stock': 'Stoc magazin',
    'product.edit.total.stock': 'Stoc total',
    
    // Category Manager
    'category.manager.no.categories': 'Nu există categorii. Adaugă prima categorie folosind butonul "Categorie nouă".',
    
    // Back to Top Button
    'back.to.top': 'Înapoi sus',
    
    // Shop
    'shop.title': 'Magazin Online',
    'shop.categories.lashes': 'Gene',
    'shop.categories.brows': 'Sprâncene',
    'shop.categories.lamination': 'Laminarea',
    'shop.categories.cosmetics': 'Cosmetice & îngrijire personală',
    'shop.currency': 'Valută',
    'shop.filters.curve': 'Curbură',
    'shop.filters.length': 'Lungime',
    'shop.filters.thickness': 'Grosime',
    'shop.filters.brand': 'Brand',
    'shop.filters.type': 'Tip',
    'shop.sort.new': 'Noutăți',
    'shop.sort.price_asc': 'Preț (crescător)',
    'shop.sort.price_desc': 'Preț (descrescător)',
    'shop.sort.bestsellers': 'Cele mai vândute',
    'shop.product.add_to_cart': 'Adaugă în coș',
    'shop.product.view_details': 'Vezi detalii',
    'shop.labels.new': 'NOU',
    'shop.labels.sale': 'Reducere',
    'shop.labels.limited': 'Stoc limitat',
    
    // Auth
    'auth.login.title': 'Autentificare',
    'auth.register.title': 'Înregistrare',
    'auth.name': 'Nume Prenume',
    'auth.birthdate': 'Data nașterii',
    'auth.phone': 'Nr de telefon',
    'auth.experience.beginner': 'Mester începător (0-1 an)',
    'auth.experience.experienced': 'Mester cu experiență',
    'auth.experience.trainer': 'Trener',
    'auth.instagram': 'Instagram (opțional)',
    'auth.country': 'Țară',
    'auth.city': 'Oraș/Raion',
    'auth.village': 'Sat',
    'auth.address': 'Adresa',
    'auth.bonus.message': 'Felicitări! Ai primit un bonus de 15% pentru prima comandă în următoarele 2 ore!',
    'auth.modal.title': 'Contul tău Adress Beauty',
    'auth.modal.description': 'Autentifică-te sau creează un cont nou pentru a continua cumpărăturile',
    'auth.email': 'Email',
    'auth.password': 'Parola',
    'auth.email.placeholder': 'adresa@email.com',
    'auth.password.placeholder': '••••••••',
    'auth.loading': 'Se încarcă...',
    'auth.login.success': 'Autentificare reușită!',
    'auth.login.error': 'Eroare la autentificare',
    'auth.register.error': 'Eroare la înregistrare',
    'auth.experience': 'Experiență',
    'auth.name.placeholder': 'Nume Prenume',
    'auth.phone.placeholder': '+373 XX XXX XXX',
    'auth.instagram.placeholder': '@username',
    'auth.city.placeholder': 'Chișinău',
    'auth.village.placeholder': '(opțional)',
    'auth.address.placeholder': 'Strada, numărul casei',
    'auth.bonus.special': '🎁 Bonus special: Primești 15% reducere pentru prima comandă dacă te înregistrezi acum! Bonusul este valabil 2 ore după înregistrare.',
    
    // Checkout
    'checkout.title': 'Finalizează comanda',
    'checkout.back': 'Înapoi la coș',
    'checkout.description': 'Completează datele pentru a finaliza comanda ta',
    'checkout.personal.info': 'Informații Personale',
    'checkout.delivery.info': 'Informații de Livrare',
    'checkout.payment.info': 'Metoda de Plată',
    'checkout.order.summary': 'Rezumatul Comenzii',
    'checkout.firstname': 'Prenume *',
    'checkout.lastname': 'Nume *',
    'checkout.email': 'Email *',
    'checkout.phone': 'Telefon *',
    'checkout.address': 'Adresa completă *',
    'checkout.city': 'Orașul *',
    'checkout.postal.code': 'Cod poștal *',
    'checkout.delivery.method': 'Metoda de livrare *',
    'checkout.payment.method': 'Metoda de plată *',
    'checkout.notes': 'Observații (opțional)',
      'checkout.submit': 'Plasează comanda',
      'checkout.submitting': 'Se procesează...',
      'checkout.email.placeholder': 'email@exemplu.com',
      'checkout.phone.placeholder': '07xx xxx xxx',
      'checkout.postal.placeholder': '123456',
    
    // Delivery
    'delivery.title': 'Livrare și Achitare',
    'delivery.description': 'Informații complete despre modalitățile de livrare, plată și politicile noastre de retur',
    'delivery.options.title': 'Opțiuni de Livrare',
    'delivery.options.description': 'Alegeți modalitatea de livrare care vi se potrivește cel mai bine',
    'delivery.payment.title': 'Metode de Achitare',
    'delivery.payment.description': 'Pentru a vă oferi flexibilitate și siguranță în procesul de cumpărare',
    'delivery.invoice.title': 'Factură Fiscală',
    'delivery.invoice.description': 'Factură fiscală se emite la cererea clientului. În acest caz, vă rugăm să ne lăsați un mesaj cu solicitarea dumneavoastră și datele necesare pentru facturare, iar echipa noastră va reveni în cel mai scurt timp.',
    'delivery.return.title': 'Politica de Retur',
    'delivery.return.description': 'Informații importante despre returnarea produselor',
    'delivery.return.restrictions': 'Restricții de Retur',
    'delivery.return.accepted': 'Când Este Acceptat Returul',
    'delivery.return.legal': 'Conformitate Legală',
    'delivery.contact.title': 'Ai întrebări despre livrare sau plată?',
    'delivery.contact.description': 'Echipa noastră este gata să te ajute cu orice întrebare',
    'delivery.contact.call': 'Sună: +373 68 88 24 90',
    'delivery.contact.email': 'Scrie-ne: addressbeauty@mail.ru',
    
    // Loyalty
    'loyalty.level1': 'De la 5.001 lei - 5% reducere',
    'loyalty.level2': 'De la 10.001 lei - 6% reducere',
    'loyalty.level3': 'De la 20.001 lei - 7% reducere',
    'loyalty.level4': 'De la 30.001 lei - 8% reducere',
    'loyalty.level5': 'De la 50.001 lei - 10% reducere',
    
    // Common
    'common.loading': 'Se încarcă...',
    'common.error': 'Eroare',
    'common.success': 'Success',
    'common.cancel': 'Anulează',
    'common.save': 'Salvează',
    'common.close': 'Închide',
  },
  RU: {
    // Header
    'header.home': 'Главная',
    'header.shop': 'Онлайн магазин',
    'header.courses': 'Курсы',
    'header.about': 'О нас',
    'header.delivery': 'Доставка / Оплата',
    'header.contact': 'Контакт',
    'header.cart': 'Корзина',
    'header.account': 'Мой аккаунт',
    'header.register': 'Регистрация',
    'header.login': 'Вход',
    'header.motto': 'Вдохновение, образование и продукты в одном месте!',
    
    // Homepage
    'home.hero.title': 'Adress Beauty',
    'home.hero.motto': 'Вдохновение, образование и продукты в одном месте!',
    'home.hero.shop': 'Онлайн Магазин',
    'home.hero.courses': 'Профессиональные Курсы',
    'home.hero.contact': 'Контакты',
    'home.why.title': 'Почему выбирают Adress Beauty?',
    'home.why.subtitle': 'Мы больше чем бренд – мы миссия по предоставлению лучших продуктов и beauty услуг в Молдове.',
    'home.shop.title': 'Профессиональный Магазин',
    'home.shop.description': 'Более 1000 премиум продуктов для наращивания ресниц, бровей и профессиональной косметики.',
    'home.shop.button': 'Изучить Продукты',
    'home.education.title': 'Качественное Образование',
    'home.education.description': '6 программ курсов, от начинающих до профессионального уровня. Признанный диплом и постоянная поддержка.',
    'home.education.button': 'Посмотреть Курсы',
    'home.services.title': 'Услуги Салона',
    'home.services.description': 'Профессиональные услуги в нашем физическом салоне с новейшими техниками и премиум продуктами.',
    'home.services.button': 'Записаться',
    'home.cta.title': 'Начни свою профессиональную трансформацию сегодня',
    'home.cta.subtitle': 'Присоединяйся к нашему сообществу beauty профессионалов и открой все, что нужно для твоего успеха.',
    'home.cta.course': 'Забронировать Курс',
    'home.cta.products': 'Изучить Продукты',
    
    // Homepage Carousel
    'home.carousel.title': 'Откройте Наши Предложения',
    'home.carousel.description': 'Эксклюзивные акции, новые продукты и образовательный контент для улучшения вашего опыта красоты',
    'home.carousel.promotion': 'Акция',
    'home.carousel.new-product': 'Новый Продукт',
    'home.carousel.video': 'Видео',
    
    // Online Store
    'store.title': 'Онлайн Магазин',
    'store.description': 'Откройте профессиональные продукты для наращивания ресниц высочайшего качества',
    'store.categories.all': 'Все',
    'store.categories.lashes': 'Ресницы',
    'store.categories.lashes.subtitle': 'Наращивание и Аксессуары',
    'store.categories.brows': 'Брови',
    'store.categories.brows.subtitle': 'Хна и Краски',
    'store.categories.lamination': 'Ламинирование',
    'store.categories.lamination.subtitle': 'Растворы и Наборы',
    'store.categories.care': 'Уход',
    'store.categories.care.subtitle': 'Косметика и Уход за кожей',
    
    // Courses
    'courses.title': 'Beauty Курсы',
    'courses.subtitle': 'В Adress Beauty мы верим в силу качественного образования.',
    'courses.description': 'Наши курсы созданы для того, чтобы предоставить не только информацию, но и реальную профессиональную трансформацию.',
    'courses.level.beginner': 'Начинающий',
    'courses.level.intermediate': 'Средний',
    'courses.level.advanced': 'Продвинутый',
    'courses.status.preparing': 'В подготовке',
    'courses.models': 'модели',
    'courses.details': 'Посмотреть Детали',
    'courses.coming.soon': 'Скоро',
    'courses.reserve': 'Забронировать Место: +373 68 88 24 90',
    'courses.email': 'Email: addressbeauty@mail.ru',
    'courses.schedule.visit': 'Запланировать Визит',
    'courses.description.title': 'Описание',
    'courses.what.learn': 'Что изучаете',
    'courses.effects.volumes': 'Эффекты и Объемы',
    'courses.what.get': 'Что получаете',
    'courses.comparison.title': 'Сравнение Курсов',
    'courses.comparison.element': 'Элемент',
    'courses.cta.title': 'Готовы начать свою профессиональную трансформацию?',
    'courses.cta.description': 'Выберите подходящий курс и сделайте первый шаг к успешной карьере в beauty!',
    'courses.call.now': 'Звоните сейчас: +373 68 88 24 90',
    'courses.write.us': 'Напишите нам: addressbeauty@mail.ru',
    
    // About
    'about.title': 'О Adress Beauty',
    'about.subtitle': 'Adress Beauty - это больше чем бренд – это миссия.',
    'about.description': 'Мы поставили цель предоставить лучшие продукты, наиболее структурированные курсы и наиболее ценимые beauty услуги в Молдове. Мы посвящены тому, чтобы превратить страсть к красоте в успешную карьеру для каждого клиента.',
    'about.achievements.clients': 'Довольных клиентов',
    'about.achievements.students': 'Выпускников курсов',
    'about.achievements.products': 'Премиум продуктов',
    'about.achievements.experience': 'Лет опыта',
    'about.mission.title': 'Наша Миссия',
    'about.mission.description': 'Предоставлять высококачественное образование, премиум продукты и исключительные услуги в области beauty, создавая сообщество страстных профессионалов, которые преобразуют жизни людей через красоту и уверенность в себе.',
    'about.vision.title': 'Наше Видение',
    'about.vision.description': 'Стать самой уважаемой и любимой beauty академией в Молдове, признанной за высокие стандарты качества, инновации и преданность успеху каждого студента и клиента.',
    'about.values.title': 'Наши Ценности',
    'about.values.subtitle': 'Принципы, которые направляют нас каждый день и в каждом взаимодействии с нашими клиентами',
    'about.team.title': 'Наша Команда',
    'about.team.subtitle': 'Преданные профессионалы с обширным опытом и страстью к совершенству',
    'about.education': 'Образование:',
    'about.age': 'Возраст:',
    'about.salon.title': 'Наш Салон',
    'about.salon.subtitle': 'Современное, чистое и расслабляющее пространство, созданное для комфорта и удовлетворения клиентов',
    'about.cta.title': 'Присоединяйтесь к Сообществу Adress Beauty',
    'about.cta.description': 'Хотите ли вы учиться, покупать премиум продукты или пользоваться нашими услугами, мы здесь для вас!',
    'about.cta.courses': 'Посмотреть Курсы',
    'about.cta.shop': 'Изучить Магазин',
    'about.cta.contact': 'Связаться с нами',
    
    // Contact
    'contact.title': 'Связаться с нами',
    'contact.description': 'Мы здесь для вас! Свяжитесь с нами по любым вопросам о курсах, продуктах или услугах. Наша команда ответит в кратчайшие сроки.',
    'contact.quick.book': 'Записаться на Консультацию',
    'contact.quick.book.desc': 'Бесплатная консультация по курсам',
    'contact.quick.order': 'Заказать Продукты',
    'contact.quick.order.desc': 'Более 1000 премиум продуктов',
    'contact.quick.info': 'Информация о Курсах',
    'contact.quick.info.desc': '6 специализированных программ',
    'contact.info.title': 'Контактная Информация',
    'contact.social.title': 'Подписывайтесь на нас',
    'contact.location.title': 'Наше Местоположение',
    'contact.map.interactive': 'Интерактивная карта',
    'contact.map.google': 'Google Maps будет интегрирована',
    'contact.map.button': 'Посмотреть в Google Maps',
    'contact.address.title': 'Adress Beauty',
    'contact.address.location': 'г. Кишинев, сек. Буюканы',
    'contact.address.street': 'ул. Костаке Негрие',
    'contact.form.title': 'Отправить нам Сообщение',
    'contact.form.name': 'Полное имя *',
    'contact.form.name.placeholder': 'Имя и фамилия',
    'contact.form.email': 'Электронная почта *',
    'contact.form.email.placeholder': 'адрес@email.com',
    'contact.form.phone': 'Телефон',
    'contact.form.phone.placeholder': '+373 XX XXX XXX',
    'contact.form.type': 'Тип вопроса',
    'contact.form.type.placeholder': 'Выберите категорию',
    'contact.form.subject': 'Тема *',
    'contact.form.subject.placeholder': 'Тема сообщения',
    'contact.form.message': 'Сообщение *',
    'contact.form.message.placeholder': 'Опишите ваш вопрос или запрос...',
    'contact.form.submit': 'Отправить Сообщение',
    'contact.form.submitting': 'Отправляется...',
    'contact.policies.title': 'Политики и Правовая Информация',
    
    // Category Products Page
    'category.search.placeholder': 'Поиск продуктов...',
    'category.filters.title': 'Фильтры',
    'category.filters.curvature': 'Изгиб',
    'category.filters.length': 'Длина',
    'category.filters.thickness': 'Толщина',
    'category.filters.brand': 'Бренд',
    'category.sort.newest': 'Новинки',
    'category.sort.price.low': 'Цена по возрастанию',
    'category.sort.price.high': 'Цена по убыванию',
    'category.sort.popular': 'Самые продаваемые',
    'category.show.all': 'Все',
    'category.show.out.of.stock': 'Показать недоступные продукты',
    'category.reset.filters': 'Сбросить Фильтры',
    'category.show.all.subcategories': 'Показать все',
    'category.hide.subcategories': 'Скрыть',
    'category.subcategories.count': 'категории',
    'category.show.less': 'Показать меньше',
    
    // Add Product Button
    'add.product.title': 'Добавить продукт',
    'add.product.description': 'Заполните данные продукта',
    'add.product.category': 'Категория',
    'add.product.category.placeholder': 'Выберите категорию',
    'add.product.continue': 'Продолжить',
    
    // Checkout Page - Additional
    'checkout.address.placeholder': 'Улица, номер, блок, лестница, этаж, квартира',
    'checkout.city.placeholder': 'Город',
    'checkout.firstname.placeholder': 'Введите имя',
    'checkout.lastname.placeholder': 'Введите фамилию',
    'checkout.notes.placeholder': 'Специальные инструкции по доставке или другие замечания...',
    'checkout.agree.terms': 'Принимаю',
    'checkout.agree.terms.link': 'условия и положения',
    'checkout.agree.privacy': 'и',
    'checkout.agree.privacy.link': 'политику конфиденциальности',
    
    // Admin Products Table
    'admin.search.placeholder': 'Поиск по названию или SKU...',
    'admin.delete.product': 'Удалить продукт',
    'admin.deleting': 'Удаление...',
    'admin.delete': 'Удалить',
    'admin.no.products': 'Продукты не найдены для текущих критериев.',
    
    // Product Page
    'product.select.variant': 'Выберите вариант',
    'product.curvature': 'Изгиб',
    'product.thickness': 'Толщина',
    'product.length': 'Длина',
    
    // Product Edit Dialog
    'product.edit.description': 'Описание',
    'product.edit.description.placeholder': 'Введите описание продукта...',
    'product.edit.image.placeholder': 'Введите URL изображения или данные Base64...',
    'product.edit.price': 'Цена (MDL)',
    'product.edit.discount': 'Скидка (%)',
    'product.edit.store.stock': 'Склад магазина',
    'product.edit.total.stock': 'Общий склад',
    
    // Category Manager
    'category.manager.no.categories': 'Категории не существуют. Добавьте первую категорию, используя кнопку "Новая категория".',
    
    // Back to Top Button
    'back.to.top': 'Наверх',
    
    // Shop
    'shop.title': 'Онлайн Магазин',
    'shop.categories.lashes': 'Ресницы',
    'shop.categories.brows': 'Брови',
    'shop.categories.lamination': 'Ламинирование',
    'shop.categories.cosmetics': 'Косметика и личный уход',
    'shop.currency': 'Валюта',
    'shop.filters.curve': 'Изгиб',
    'shop.filters.length': 'Длина',
    'shop.filters.thickness': 'Толщина',
    'shop.filters.brand': 'Бренд',
    'shop.filters.type': 'Тип',
    'shop.sort.new': 'Новинки',
    'shop.sort.price_asc': 'Цена (по возрастанию)',
    'shop.sort.price_desc': 'Цена (по убыванию)',
    'shop.sort.bestsellers': 'Бестселлеры',
    'shop.product.add_to_cart': 'Добавить в корзину',
    'shop.product.view_details': 'Подробнее',
    'shop.labels.new': 'НОВИНКА',
    'shop.labels.sale': 'Скидка',
    'shop.labels.limited': 'Ограниченный запас',
    
    // Auth
    'auth.login.title': 'Вход',
    'auth.register.title': 'Регистрация',
    'auth.name': 'Имя Фамилия',
    'auth.birthdate': 'Дата рождения',
    'auth.phone': 'Номер телефона',
    'auth.experience.beginner': 'Начинающий мастер (0-1 год)',
    'auth.experience.experienced': 'Опытный мастер',
    'auth.experience.trainer': 'Тренер',
    'auth.instagram': 'Instagram (необязательно)',
    'auth.country': 'Страна',
    'auth.city': 'Город/Район',
    'auth.village': 'Село',
    'auth.address': 'Адрес',
    'auth.bonus.message': 'Поздравляем! Вы получили бонус 15% на первый заказ в следующие 2 часа!',
    'auth.modal.title': 'Ваш аккаунт Adress Beauty',
    'auth.modal.description': 'Войдите или создайте новый аккаунт для продолжения покупок',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.email.placeholder': 'адрес@email.com',
    'auth.password.placeholder': '••••••••',
    'auth.loading': 'Загрузка...',
    'auth.login.success': 'Вход выполнен успешно!',
    'auth.login.error': 'Ошибка при входе',
    'auth.register.error': 'Ошибка при регистрации',
    'auth.experience': 'Опыт',
    'auth.name.placeholder': 'Имя Фамилия',
    'auth.phone.placeholder': '+373 XX XXX XXX',
    'auth.instagram.placeholder': '@username',
    'auth.city.placeholder': 'Кишинев',
    'auth.village.placeholder': '(необязательно)',
    'auth.address.placeholder': 'Улица, номер дома',
    'auth.bonus.special': '🎁 Специальный бонус: Получите 15% скидку на первый заказ, если зарегистрируетесь сейчас! Бонус действителен 2 часа после регистрации.',
    
    // Checkout
    'checkout.title': 'Оформить заказ',
    'checkout.back': 'Назад в корзину',
    'checkout.description': 'Заполните данные для оформления заказа',
    'checkout.personal.info': 'Личная информация',
    'checkout.delivery.info': 'Информация о доставке',
    'checkout.payment.info': 'Способ оплаты',
    'checkout.order.summary': 'Сводка заказа',
    'checkout.firstname': 'Имя *',
    'checkout.lastname': 'Фамилия *',
    'checkout.email': 'Электронная почта *',
    'checkout.phone': 'Телефон *',
    'checkout.address': 'Полный адрес *',
    'checkout.city': 'Город *',
    'checkout.postal.code': 'Почтовый индекс *',
    'checkout.delivery.method': 'Способ доставки *',
    'checkout.payment.method': 'Способ оплаты *',
    'checkout.notes': 'Примечания (необязательно)',
      'checkout.submit': 'Разместить заказ',
      'checkout.submitting': 'Обрабатывается...',
      'checkout.email.placeholder': 'email@example.com',
      'checkout.phone.placeholder': '07xx xxx xxx',
      'checkout.postal.placeholder': '123456',
    
    // Delivery
    'delivery.title': 'Доставка и Оплата',
    'delivery.description': 'Полная информация о способах доставки, оплаты и нашей политике возврата',
    'delivery.options.title': 'Варианты Доставки',
    'delivery.options.description': 'Выберите способ доставки, который вам больше всего подходит',
    'delivery.payment.title': 'Способы Оплаты',
    'delivery.payment.description': 'Чтобы обеспечить вам гибкость и безопасность в процессе покупки',
    'delivery.invoice.title': 'Налоговая Накладная',
    'delivery.invoice.description': 'Налоговая накладная выдается по запросу клиента. В этом случае, пожалуйста, оставьте нам сообщение с вашим запросом и необходимыми данными для выставления счета, и наша команда ответит в кратчайшие сроки.',
    'delivery.return.title': 'Политика Возврата',
    'delivery.return.description': 'Важная информация о возврате товаров',
    'delivery.return.restrictions': 'Ограничения Возврата',
    'delivery.return.accepted': 'Когда Возврат Принимается',
    'delivery.return.legal': 'Правовое Соответствие',
    'delivery.contact.title': 'Есть вопросы о доставке или оплате?',
    'delivery.contact.description': 'Наша команда готова помочь вам с любыми вопросами',
    'delivery.contact.call': 'Звоните: +373 68 88 24 90',
    'delivery.contact.email': 'Напишите нам: addressbeauty@mail.ru',
    
    // Loyalty
    'loyalty.level1': 'От 5.001 лей - 5% скидка',
    'loyalty.level2': 'От 10.001 лей - 6% скидка',
    'loyalty.level3': 'От 20.001 лей - 7% скидка',
    'loyalty.level4': 'От 30.001 лей - 8% скидка',
    'loyalty.level5': 'От 50.001 лей - 10% скидка',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.close': 'Закрыть',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('RO');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['RO']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};